### ISSUE TITLE
🕊️ Roadmap Page Layout

### ISSUE THREAD

**Issue by strong-minsu** [DKU-SuSuHan/frontend#23]
## 📜 이슈 내용
- 로그인 후 여행 상세 로드맵 페이지

## 📃 상세 내용
- 로그인 후 홈(여행 리스트 페이지)에서 선택된 여행의 상세 로드맵 페이지를 구현한다.

## ✅ 체크리스트
- [x] 헤더
- [x] 지도 컴포넌트 (임시 사진 첨부)
- [x] day 별 여행 장소 리스트
- [x] 수기 작성(장소 등록) 버튼

## 📌 레퍼런스
